language: objective-c

branches:
  only:
  - alfa
  - beta
  - stable
  - master

os: osx

rvm:
- 2.6

cache:
  directories:
  - ./Unity

before_install:
- chmod a+x ./Travis/install.sh
- chmod a+x ./Travis/build.sh
- chmod a+x ./Travis/tag.sh

install:
- ./Travis/install.sh

script:
- ./Travis/build.sh

after_success:
- ./Travis/tag.sh
- ./deploy.sh

deploy:
- provider: releases
  api_key: $GITHUB_TOKEN
  file: 
  - Build/windows.zip
  - Build/linux.tar.gz
  - Build/osx.dmg
  name: $TRAVIS_BRANCH $(date +'%Y.%m.%d %H:%M')
  skip_cleanup: true
  on:
    all_branches: true

- provider: pages
  edge:
    branch: v1.8.47
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: Build/webgl
  on:
    branch:
      - master    
      - stable
